/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "text.h"

bool_t
xdr_Data (XDR *xdrs, Data *objp)
{
    register int32_t *buf;

    int i;
     if (!xdr_vector (xdrs, (char *)objp->Buffer, 1048576,
        sizeof (u_char), (xdrproc_t) xdr_u_char))
         return FALSE;
     if (!xdr_u_char (xdrs, &objp->prog))
         return FALSE;
    return TRUE;
}
