/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "text.h"
#include <QGraphicsPixmapItem>
#include "qtextcodec.h"
#include <QColor>
#include <QRgb>
//#include <QMessageBox>

Data *
binaryzuj_1_svc(Data *argp, struct svc_req *rqstp)
{
    static Data  result;

    //---LOG---
    //uchar nowa[1024][1024];
    printf("Otrzymano tablice \n");
    /*
    for(int i=0; i<1024; i++) {
        for(int j=0; j<1024; j++) {
            nowa[i][j] = argp->Buffer[i*1024 + j];
            printf("%d ", nowa[i][j]);
        }
        printf("\n");
    }
    */

    printf("Wyslano tablice \n");
    for(int i=0; i<1048576; i++) {
        if(argp->Buffer[i] >= argp->prog) {
            result.Buffer[i] = 255;
        }
        else {
            result.Buffer[i] = 0;
        }
        //---LOG---
        //printf("%d ", result.Buffer[i]);
    }
    printf("\n");

    return &result;
}
