/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Data {
    u_char Buffer[1048576];
    u_char prog;
};
typedef struct Data Data;

#define TEXT_PROG 0x23000001
#define TEXT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define Binaryzuj 1
extern  Data * binaryzuj_1(Data *, CLIENT *);
extern  Data * binaryzuj_1_svc(Data *, struct svc_req *);
extern int text_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Binaryzuj 1
extern  Data * binaryzuj_1();
extern  Data * binaryzuj_1_svc();
extern int text_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Data (XDR *, Data*);

#else /* K&R C */
extern bool_t xdr_Data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
